= FreeGazami
:toc:
:sectnums:

== Repo Overview
```txt
.
├── crustlet
├── gazami
├── Makefile
└── README.adoc
```

=== crustlet
====
Bootloader repository as a submodule
====

=== gazami
====
Kernel repository as a submodule
====

=== Makefile
====
configuration file for make
====

== Software Requirements

=== Linux Host
Any Linux distro should work.
You'll most likely have to modify the Makefile and/or source to make things work on Windows or MacOS.

=== make
make is the build system for this project for now. (subject to change)

=== Nightly Rust
Nightly rust provides custom allocators, linker formats, and targets(bare-metal x86_64) and stuff like that.

=== jq
Used in the main Makefile to parse JSON files that carry build/meta info.
jq is sually installed on most Linux distros by default but you should check.


== How to build

[NOTE]
====
Each time a build is run for either the kernel or bootloader, a JSON file is generated in that repo.
The JSON file in these repos are used to pass build info (like build triple, package name, bin name, etc.) which is used by the make process in free-gazami.
Makefile in free-gazami uses the JSON files from the kernel and bootloader repo to generate disk image names and variable names to use when running qemu.
I am very open to suggestions on how to improve this build system.
====

=== basic build
kernel and bootloader
[source,bash]
```bash
make build
```

=== build the bootloader
[source,bash]
```bash
make build-crustlet
```

=== build the kernel
[source,bash]
```bash
make build-gazami
```

=== build a bootable disk image
This builds both the kernel and bootloader
[source,bash]
```bash
make create-img
```

=== build a bootable disk image, and boot from the disk image on qemu
This builds both the kernel and bootloader
[source,bash]
```bash
make run-qemu
```


== Hardware Support
Only #Qemu x86_64# at this moment