= FreeGazami
:toc:
:sectnums:

== Repo Overview
```txt
.
├── crustlet
├── gazami
├── Makefile
└── README.adoc
```

=== crustlet
====
Bootloader repository as a submodule
====

=== gazami
====
Kernel repository as a submodule
====

=== Makefile
====
configuration file for make
====


== How to build

[NOTE]
====
Each time a build is run for either the kernel or bootloader, a JSON file is generated in that repo.
The JSON file in these repos are used to pass build info (like build triple, package name, bin name, etc.) which is used by the make process in free-gazami.
Makefile in free-gazami uses the JSON files from the kernel and bootloader repo to generate disk image names and variable names to use when running qemu.
I am very open to suggestions on how to improve this build system.
====

=== basic build
kernel and bootloader
[source,bash]
```bash
make build
```

=== build the bootloader
[source,bash]
```bash
make build-crustlet
```

=== build the kernel
[source,bash]
```bash
make build-gazami
```

=== build a bootable disk image
This builds both the kernel and bootloader
[source,bash]
```bash
make create-img
```

=== build a bootable disk image, and boot from the disk image on qemu
This builds both the kernel and bootloader
[source,bash]
```bash
make run-qemu
```


== Hardware Support
Only #Qemu x86_64# at this moment